[package]
name = "imagehash"
version = "0.1.0"
authors = ["Chad Austin <chad@chadaustin.me>"]
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
vcpkg = "*"

[dependencies]
anyhow = "*"
async-std = { version = "*", features = ["unstable"] }
blake3 = "*"
blockhash = "*"
crossbeam = "*"
crossbeam-channel = "*"
directories = "*"
futures = "*"
hex = "*"
img_hash = "*"
jwalk = "*"
libheif-rs = "*"
num_cpus = "*"
rayon = "*"
sha-1 = "*"
structopt = "*"
tokio = { version = "1", features = ["full"] }
walkdir = "2"
wild = "*"

[target.'cfg(windows)'.dependencies]
rusqlite = { version = "*", features = ["bundled"] }

[target.'cfg(not(windows))'.dependencies]
rusqlite = "*"
