[package]
name = "imagehash"
version = "0.1.0"
authors = ["Chad Austin <chad@chadaustin.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
tokio = { version = "0.2", features = ["full"] }
crossbeam = "*"
crossbeam-channel = "*"
rayon = "*"
futures = "*"
anyhow = "*"
sha-1 = "*"
num_cpus = "*"
hex = "*"
sqlite = "*"
structopt = "*"
blake3 = "*"
directories = "*"
