[package]
name = "photohash"
version = "0.1.0"
authors = ["Chad Austin <chad@chadaustin.me>"]
edition = "2021"
build = "build.rs"
license = "GPL-3.0"
description = "Tool for detecting duplicate photos and diffing directories"
repository = "https://github.com/chadaustin/photohash"

[lib]
name = "photohash"
path = "src/lib.rs"

[[bin]]
name = "photohash"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "662dbb50e63af15baa2909b7eac5b1b87e86a0aa"
dependencies = [
    "libheif:x64-windows",
]

[profile.release-with-debug]
inherits = "release"
debug = true

[build-dependencies]
vcpkg = "*"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "databasebench"
harness = false

[dependencies]
anyhow = "*"
async-std = { version = "*", features = ["unstable"] }
blake3 = "*"
blockhash = "*"
chrono = "*"
directories = "*"
dunce = "*"
kamadak-exif = "*"
keepawake = "*"
futures = "*"
hex = "*"
image = { version = "*", features = [] }
image_hasher = "*"
jwalk = "*"
ntapi = "*"
libheif-rs = "*"
rayon = "*"
rusqlite_migration = "*"
self_cell = "*"
static_assertions = "*"
structopt = "*"
thiserror = "*"
tokio = { version = "1", features = ["full"] }
turbojpeg = { version = "*", features = ["image"] }
walkdir = "2"
wild = "*"
winapi = { version = "*", features = ["heapapi"] }

[target.'cfg(windows)'.dependencies]
rusqlite = { version = "*", features = ["bundled"] }

[target.'cfg(not(windows))'.dependencies]
rusqlite = "*"
