[package]
name = "imagehash"
version = "0.1.0"
authors = ["Chad Austin <chad@chadaustin.me>"]
edition = "2018"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
vcpkg = "*"

[dependencies]
walkdir = "2"
tokio = { version = "1", features = ["full"] }
crossbeam = "*"
crossbeam-channel = "*"
rayon = "*"
futures = "*"
anyhow = "*"
sha-1 = "*"
num_cpus = "*"
hex = "*"
structopt = "*"
blake3 = "*"
directories = "*"

libheif-rs = "0.18"
blockhash = "*"
img_hash = "*"

[target.'cfg(windows)'.dependencies]
rusqlite = { version = "*", features = ["bundled"] }

[target.'cfg(not(windows))'.dependencies]
rusqlite = "*"
