on: [push, pull_request]

name: CI

env:
  RUST_BACKTRACE: 1

jobs:
  test:
    strategy:
      matrix:
        image:
          - ubuntu-24.04
          # TODO: Figure out how to install libheif on macOS.
          # - macos-latest # ARM
          # - macos-13 # Intel
          # Windows will require extra attention.
          # - windows-latest

    runs-on: ${{ matrix.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install Ubuntu packages
        run: sudo apt install -y libheif-dev nasm
      - run: cargo test
